{% set name = "cwinpy" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1eae6de507023b037f63ef75ca2fe83c3324de435fe744052446ca5942e6d898
  patches:
    # we handle lalsuite packages individually
    - requirements-no-lalsuite.patch

build:
  entry_points:
    - cwinpy_pe = cwinpy.pe.pe:pe_cli
    - cwinpy_pe_pipeline = cwinpy.pe.pe:pe_pipeline_cli
    - cwinpy_pe_generate_pp_plots = cwinpy.pe.testing:generate_pp_plots
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # requirements aren't available for Windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - appdirs
    - astropy
    - bilby >=1.1.4
    - configargparse
    - corner >=2.2.1
    - gwosc >=0.5.4
    - gwpy >=2.1.1
    - htcondor >=9.0.6
    - lintegrate >=0.1.7
    - matplotlib-base
    - numba >=0.5.0
    - {{ pin_compatible('numpy') }}
    - pesummary >=0.13.0
    - psrqpy >=1.2.2
    - pycondor
    - python
    - python-lal >=7.1.7
    - python-lalframe >=2.0.0
    - python-lalpulsar >=4.0.0
    - requests
    - scipy

test:
  requires:
    - lalapps
    - pip
    - pytest
    - pytest-socket
  commands:
    # check requirements
    - python -m pip check
    # run unit tests
    - python -m pytest -ra -v
    # check entry points
    - cwinpy_pe --help
    - cwinpy_pe_pipeline --help
    - cwinpy_pe_generate_pp_plots --help

about:
  home: https://github.com/cwinpy/cwinpy/
  doc_url: https://cwinpy.readthedocs.io/
  dev_url: https://git.ligo.org/cwinpy/cwinpy
  license: MIT
  license_file: LICENSE
  summary: CW Inference in Python
  description: |
    A Python module for performing Bayesian inference for
    continuous gravitational-wave signals from pulsars.

extra:
  recipe-maintainers:
    - mattpitkin
    - duncanmmacleod
