{% set name = "cwinpy" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b766a79675b6b8607fa4c1023de97f26693dc32764f9965f36c028f70f057193

build:
  entry_points:
    - cwinpy_pe = cwinpy.pe.pe:pe_cli
    - cwinpy_pe_dag = cwinpy.pe.pe:pe_dag_cli
    - cwinpy_pe_generate_pp_plots = cwinpy.pe.testing:generate_pp_plots
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy
    - bilby >=0.5.8
    - bilby_pipe >=0.2.0
    - gwpy
    - lintegrate
    - matplotlib-base
    - numba
    - numpy >=1.15
    - pycondor
    - python >=3.6
    - python-lal
    - python-lalpulsar
    - scipy

test:
  imports:
    - cwinpy
  commands:
    - cwinpy_pe --help
    - cwinpy_pe_dag --help
    - cwinpy_pe_generate_pp_plots --help

about:
  home: https://github.com/cwinpy/cwinpy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CW Inference in Python
  doc_url: https://cwinpy.readthedocs.io/en/latest/
  dev_url: https://github.com/cwinpy/cwinpy/
  description: |
    A Python module for performing Bayesian inference for continuous gravitational-wave signals from pulsars.

extra:
  recipe-maintainers:
    - mattpitkin
    - duncanmmacleod
