{% set name = "cwinpy" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdc0cbdc5d96329fb0424ec462d10a2f7b0a002d7b6de10e65fd955d53335d5f
  patches:
    # we handle lalsuite packages individually
    - requirements-no-lalsuite.patch
    # exclude test directory as a package
    - packages.patch
    # remove march=native
    - march.patch

build:
  entry_points:
    - cwinpy_pe = cwinpy.pe.pe:pe_cli
    - cwinpy_pe_dag = cwinpy.pe.pe:pe_dag_cli
    - cwinpy_pe_generate_pp_plots = cwinpy.pe.testing:generate_pp_plots
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # requirements aren't available for Windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - astropy
    - bilby >=1.0.0
    - bilby_pipe >=1.0.0
    - configargparse
    - ephem
    - gwosc
    - gwpy
    - libstempo >=2.4.2
    - lintegrate
    - matplotlib-base
    - numba
    - {{ pin_compatible('numpy') }}
    - psrqpy
    - pycondor
    - python
    - python-lal >=7.1.2
    - python-lalframe >=1.5.4
    - python-lalpulsar >=3.0.1
    - scipy
    - tempo2 <2022.01.1

test:
  requires:
    - lalapps
    - pip
    - pytest
    - pytest-socket
  source_files:
    - test/
  commands:
    # check requirements
    - python -m pip check
    # run unit tests
    - python -m pytest test/ -ra -v
    # check entry points
    - cwinpy_pe --help
    - cwinpy_pe_dag --help
    - cwinpy_pe_generate_pp_plots --help

about:
  home: https://github.com/cwinpy/cwinpy/
  doc_url: https://cwinpy.readthedocs.io/
  dev_url: https://github.com/cwinpy/cwinpy.git
  license: MIT
  license_file: LICENSE
  summary: CW Inference in Python
  description: |
    A Python module for performing Bayesian inference for
    continuous gravitational-wave signals from pulsars.

extra:
  recipe-maintainers:
    - mattpitkin
    - duncanmmacleod
