{% set name = "cwinpy" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f047c6ec0c82a57a68d232c57e7cd29e297c925a6565d1ed9536a0e4645f137d
  patches:
    # we handle lalsuite packages individually
    - requirements-no-lalsuite.patch
    # one test fails if no iternet connection is possible, so patch
    - nointernet.patch

build:
  entry_points:
    - cwinpy_pe = cwinpy.pe.pe:pe_cli
    - cwinpy_pe_pipeline = cwinpy.pe.pe:pe_pipeline_cli
    - cwinpy_pe_generate_pp_plots = cwinpy.pe.testing:generate_pp_plots
  ignore_run_exports:
    - numpy
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # requirements aren't available for Windows and Python < 3.9
  skip: true  # [win or py<39]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - appdirs
    - arby
    - astropy-base
    - bilby >=2.0.1
    - configargparse
    - corner >=2.2.1
    - gwosc >=0.5.4
    - gwpy >=2.1.1
    - healpy
    - lintegrate >=0.1.7
    - matplotlib-base >=3.6.0
    - numba >=0.5.0
    - numpy >=1.17.0
    - pesummary >=1.1.1
    - psrqpy >=1.1.7
    - python
    - python-htcondor >=10.0.0
    - python-lal >=7.2.2
    - python-lalframe >=2.0.3
    - python-lalpulsar >=5.0.2
    - requests
    - scipy
    - simpleeval
    - solar_system_ephemerides >=1.0.0

test:
  requires:
    - arby
    - cweqgen >=0.4.4
    - healpy
    - httpretty
    - libstempo >=2.4.5  # [not arm64]
    - lalapps
    - pip
    - pytest >=4.6
    - pytest-astropy
    - pytest-socket
    - seaborn
  commands:
    # check requirements
    - python -m pip check  # [not arm64]
    # run unit tests
    - python -m pytest --pyargs cwinpy.test -ra  # [build_platform == target_platform]
    # check entry points
    - cwinpy_pe --help
    - cwinpy_pe_pipeline --help
    - cwinpy_pe_generate_pp_plots --help

about:
  home: https://github.com/cwinpy/cwinpy/
  doc_url: https://cwinpy.readthedocs.io/
  dev_url: https://git.ligo.org/cwinpy/cwinpy
  license: MIT
  license_file: LICENSE
  summary: CW Inference in Python
  description: |
    A Python module for performing Bayesian inference for
    continuous gravitational-wave signals from pulsars.

extra:
  recipe-maintainers:
    - mattpitkin
    - duncanmmacleod
