{% set name = "cwinpy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b37ade22c6dbfdb66a1cc523edd24546e3cc1a598824922e34073bc314e85976
  patches:
    # we handle lalsuite packages individually
    - requirements-no-lalsuite.patch
    # exclude test directory as a package
    - packages.patch

build:
  entry_points:
    - cwinpy_pe = cwinpy.pe.pe:pe_cli
    - cwinpy_pe_dag = cwinpy.pe.pe:pe_dag_cli
    - cwinpy_pe_generate_pp_plots = cwinpy.pe.testing:generate_pp_plots
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  # requirements aren't available for Windows
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - astropy
    - bilby >=0.5.8
    - bilby_pipe >=0.2.0
    - configargparse
    - gwosc
    - gwpy
    - lintegrate
    - matplotlib-base
    - numba
    - {{ pin_compatible('numpy') }}
    - psrqpy
    - pycondor
    - python
    - python-lal >=7.1.2
    - python-lalframe >=1.5.4
    - python-lalpulsar >=3.0.1
    - scipy

test:
  requires:
    - lalapps
    - pip
    - pytest
    - pytest-socket
  source_files:
    - test/
  commands:
    # check requirements
    - python -m pip check
    # run unit tests
    - python -m pytest test/ -ra -v
    # check entry points
    - cwinpy_pe --help
    - cwinpy_pe_dag --help
    - cwinpy_pe_generate_pp_plots --help

about:
  home: https://github.com/cwinpy/cwinpy/
  doc_url: https://cwinpy.readthedocs.io/
  dev_url: https://github.com/cwinpy/cwinpy.git
  license: MIT
  license_file: LICENSE
  summary: CW Inference in Python
  description: |
    A Python module for performing Bayesian inference for
    continuous gravitational-wave signals from pulsars.

extra:
  recipe-maintainers:
    - mattpitkin
    - duncanmmacleod
