{% set name = "cwinpy" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e0ab18cdc0bc757d43edf1e229154f6b44d1c33360c20ac77085a157fa75b8d
  patches:
    # we handle lalsuite packages individually
    - requirements-no-lalsuite.patch

build:
  entry_points:
    - cwinpy_pe = cwinpy.pe.pe:pe_cli
    - cwinpy_pe_pipeline = cwinpy.pe.pe:pe_pipeline_cli
    - cwinpy_pe_generate_pp_plots = cwinpy.pe.testing:generate_pp_plots
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  # requirements aren't available for Windows
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - appdirs
    - astropy
    - bilby >=1.2.0
    - configargparse
    - corner >=2.2.1
    - gwosc >=0.5.4
    - gwpy >=2.1.1
    - healpy
    - lintegrate >=0.1.7
    - matplotlib-base >=3.1,!=3.6.1
    - numba >=0.5.0
    - {{ pin_compatible('numpy') }}
    - pesummary >=0.13.0
    - psrqpy >=1.2.2
    - python
    - python-htcondor >=9.0.6
    - python-lal >=7.2.2
    - python-lalframe >=2.0.3
    - python-lalpulsar >=5.0.2
    - requests
    - scipy

test:
  requires:
    - cweqgen >=0.4.4
    - healpy
    - libstempo >=2.4.5  # [not arm64]
    - lalapps
    - pip
    - pytest >=4.6
    - pytest-socket
    - seaborn
  commands:
    # check requirements
    - python -m pip check  # [not arm64]
    # run unit tests
    - python -m pytest --pyargs cwinpy  # [not arm64]
    # check entry points
    - cwinpy_pe --help
    - cwinpy_pe_pipeline --help
    - cwinpy_pe_generate_pp_plots --help

about:
  home: https://github.com/cwinpy/cwinpy/
  doc_url: https://cwinpy.readthedocs.io/
  dev_url: https://git.ligo.org/cwinpy/cwinpy
  license: MIT
  license_file: LICENSE
  summary: CW Inference in Python
  description: |
    A Python module for performing Bayesian inference for
    continuous gravitational-wave signals from pulsars.

extra:
  recipe-maintainers:
    - mattpitkin
    - duncanmmacleod
